apiVersion: v1
kind: Template
metadata:
  name: zipkin-server-template
objects:
- kind: Route
  apiVersion: v1
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    host: workshop.apps.tlk.im
    path: "/${APP_NAME}"
    port:
      targetPort: ${APP_PORT}-tcp
    to:
      kind: Service
      name: ${APP_NAME}
parameters:
- name: APP_NAME
  description: The name assigned to all of the application objects defined in this template.
  displayName: Application Name
  required: true
  value: zipkin-server