kind: BuildConfig
apiVersion: v1
metadata:
  name: service-sti-builder
spec:
  source:
    type: Git
    git:
      uri: https://github.com/platform-guild/openshift-workshop.git
    contextDir:
      openshift/services-sti
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: service-sti-builder:latest
  triggers:
  - type: ConfigChange

---

apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: service-sti-builder
  name: service-sti-builder
