---
apiVersion: v1
kind: Template
metadata:
  name: service-webhook-secret
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    labels:
      app: openshift-workshop
    name: service-webhook-secret
  data:
    WebHookSecretKey: c2VjcmV0dmFsdWUx
