server:
  port: 8082
  context-path: /logistics-service
spring:
  application:
    name: logistics-service
  zipkin:
    base-url: http://localhost:9000

---

server:
  port: 8080
spring:
  profiles: dev
  zipkin:
    base-url: http://zipkin-server:9000
