server:
  port: 8081
  context-path: /user-service
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:
      percentage: 1.0

---

server:
  port: 8080
spring:
  profiles: dev
  zipkin:
    base-url: http://zipkin-server:9000

