server:
  port: 8080
  context-path: /order-service

spring:
  application:
    name: order-service
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:
      percentage: 1.0

info:
  app:
    name: Order Service
    protocol: http
    description: 'This is the Order Service demo. GitHub: https://github.com/APIGuild/api-workshop-105'
  version: 1.0.0
  contact:
    author: API Guild
    email: '***-api-guild@thoughtworks.com'

management:
  security:
    enabled: false
endpoints:
  health:
    sensitive: false

user:
  service:
    name: UserService
    baseUrl: http://localhost:8081/user-service
    username: apiuser
    password: password
    poolSize: 20
    timeout: 5000
logistics:
  service:
    name: LogisticsService
    baseUrl: http://localhost:8082/logistics-service
    username: apiuser
    password: password
    poolSize: 20
    timeout: 5000
product:
  service:
    name: ProductService
    baseUrl: http://localhost:8083/product-service
    username: apiuser
    password: password
    poolSize: 20
    timeout: 5000

---

server:
  port: 8080
spring:
  profiles: dev
  zipkin:
    base-url: http://zipkin-server:9000
user:
  service:
    baseUrl: http://user-service:8080/user-service
logistics:
  service:
    baseUrl: http://logistics-service:8080/logistics-service
product:
  service:
    baseUrl: http://product-service:8080/product-service
