server:
  port: 8083
  context-path: /product-service
spring:
  application:
    name: product-service
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:
      percentage: 1.0

---

server:
  port: 8080
spring:
  profiles: dev
  zipkin:
    base-url: http://zepkin-server:9000
